//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartB.UI.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public int ProductId { get; set; }
        public System.DateTime BuyTime { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
