//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartB.UI.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParseInfo
    {
        public int Id { get; set; }
        public Nullable<int> MarketId { get; set; }
        public string ParseLink { get; set; }
        public int ParseType { get; set; }
        public string ProductNameXpath { get; set; }
        public string PriceXpath { get; set; }
        public string DetailLinkXpath { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Market Market { get; set; }
    }
}
